language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
 - yarn build --base-href https://petruk1.github.io/travis-example/


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
<<<<<<< HEAD
  on:
    branch: master
=======
  on: 
    branch: master
>>>>>>> bab18bd996aa1273c5700fce146efab5bf7d1dd0
